---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: golang:1.17
    commands:
      - mkdir web/dist
      - echo 0 > web/dist/test.txt
      - go test ./...
      - go build -o /dev/null github.com/kabaliserv/filex/cmd/kbs-filex

  - name: build-front
    image: node:lts-buster
    commands:
      - sh scripts/build-front.sh

  - name: build-server
    image: golang:1.17
    commands:
      - sh scripts/build-server.sh
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: "set version"
    image: bitnami/git
    commands:
      - export GIT_COMMIT_ID=$(git log --format="%H" -n 1 | egrep -o '[[:digit:]]{7}' | head -n1)
      - export GIT_TAG=$(git tag | sort -V | tail -1)
      - if [ -z "$GIT_TAG" ]; then echo -n "$GIT_COMMIT_ID"; else echo -n "$GIT_TAG-$GIT_COMMIT_ID"; fi > .tags

  - name: publish
    image: plugins/docker:20.10
    settings:
      dockerfile: docker/Dockerfile
      repo: wilsonkbs/filex
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag