---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: golang:1.17
    commands:
      - go test ./...
      - go build -o /dev/null github.com/kabaliserv/filex/cmd/kbs-filex

  - name: build-front
    image: node:lts-buster
    commands:
      - sh scripts/build-front.sh

  - name: build-server
    image: golang:1.17
    commands:
      - sh scripts/build-server.sh
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: publish
    image: plugins/docker:18
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile
      repo: kabaliserv/filex
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag