// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kabaliserv/filex/cmd/kbs-filex/config"
	"github.com/kabaliserv/filex/handler/api"
	"github.com/kabaliserv/filex/handler/web"
	"github.com/kabaliserv/filex/service/token"
	"github.com/kabaliserv/filex/store/files"
	"github.com/kabaliserv/filex/store/sessions"
	"github.com/kabaliserv/filex/store/users"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	uploadOption := provideUploadOptions(config2)
	manager := token.New()
	storeOption := provideStoreOption(config2)
	db, err := provideDatabase(storeOption)
	if err != nil {
		return application{}, err
	}
	userStore := users.NewUserStore(db, storeOption)
	sessionStore := sessions.NewSessionStore(db, storeOption)
	fileStore := files.NewFileStore(db, storeOption)
	server := api.New(uploadOption, manager, userStore, sessionStore, fileStore)
	options := provideServerOptions(config2)
	webServer := web.New(options)
	mainHealthzHandler := provideHealthz()
	mux := provideRouter(server, webServer, mainHealthzHandler)
	serverServer := provideServer(mux, config2)
	mainApplication := newApplication(serverServer)
	return mainApplication, nil
}
