// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kabaliserv/filex/cmd/kbs-filex/config"
	"github.com/kabaliserv/filex/handler/api"
	"github.com/kabaliserv/filex/handler/web"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	storeOption := provideStoreOption(config2)
	store := provideStore(storeOption)
	server := api.New(store)
	options := provideServerOptions(config2)
	webServer := web.New(options)
	mux := provideRouter(server, webServer)
	serverServer := provideServer(mux, config2)
	mainApplication := newApplication(serverServer)
	return mainApplication, nil
}
