version: "3"
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.dev-server
    ports:
      - "3000:80"
    working_dir: /go/src/github.com/kabaliserv/filex
    volumes:
      - "..:/go/src/github.com/kabaliserv/filex"
      - "../tmp/serverData:/data"
    environment:
      - FILEX_S3_BUCKET=filex
      - FILEX_S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY=minio
      - AWS_SECRET_KEY=minio123
      - AWS_REGION=us-east-1
    depends_on:
      - minio
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev-web
    ports:
      - "3001:3001"
    volumes:
      - ../web:/usr/src/filex-web
    command: "./start-dev.sh"

  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=filex
    volumes:
      - minio:/data
volumes:
  minio:
    driver: local